# Generated by Django 3.2.6 on 2021-09-10 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewerMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched', models.IntegerField(null=True)),
                ('favourite', models.IntegerField(null=True)),
                ('rating', models.IntegerField(null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.movie')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.viewer')),
            ],
        ),
    ]
